apiVersion: apps/v1
kind: Deployment
metadata:
  name: elvisweb-deployments
  labels:
        app: elvisweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elvisweb 
  template:
    metadata:
      labels:
        app: elvisweb
    spec:
      containers:
      - name: elvisweb
        image: elvisdomain/elvis-project
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: elvisweb-services
spec:
  selector:
    app: elvisweb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000
      nodePort: 30000
      

